### ISSUE TITLE
Add ability to use tab to complete like IDEs and youcompleteme

### ISSUE THREAD

**Issue by dylan-chong** [maralla/completor.vim#10]
Not sure if this is worth implementing or not but might be useful

**Comment by josefson** [comment]
Well, my installation is working with tab completion. Maybe it's supertab working over it tho.

**Comment by dylan-chong** [comment]
That's weird. I'm not using supertab, but I do have this in my .vimrc

```vimscript
set expandtab
set softtabstop=4
set shiftwidth=4
set tabstop=4

```

**Comment by josefson** [comment]
Well, as far as i know vim by default doesn't use tab for walking over and back on the popup list, instead one should use C-p or C-n. However, one can emulate the tab behavior by mapping it to those key binds, which is exactly what supertab does.
Regarding your configuration about tab, as far as i know it doesn't have anything to do with popup completion. It is just for tabs when used in insert mode, which is what you are doing it(hit tab get 4 spaces).

**Comment by dylan-chong** [comment]
Ah ok, thanks
