### ISSUE TITLE
Set python path to active virtualenv

### ISSUE THREAD

**Issue by williamsmj** [maralla/completor.vim#100]
Is it possible to do something like
```
let g:completor_python_binary = `which python`
```
to ensure completor and jedi use the currently active virtualenv for completion?

[Sorry, I realize this is possibly a very simple vim question rather than a subtle completor question!]

**Comment by maralla** [comment]
If jedi is installed in your current virtualenv you can just do:
```vim
let g:completor_python_binary = 'python'
```
or do not set this variable at all.

**Comment by thiswind** [comment]
great!! it works!
