### ISSUE TITLE
Tern does not work

### ISSUE THREAD

**Issue by aliev** [maralla/completor.vim#106]
I did `make js` as described in README, and added node path to my vimrc:

let g:completor_node_binary = '/usr/local/bin/node'

```
➜  cd /Users/apple/.vim/plugged/completor.vim/pythonx/completers/javascript && ls
__init__.py     __init__.pyc    node_modules    package.json    tern_wrapper.js
➜  javascript git:(master) node tern_wrapper.js
^C
(no errors here)
➜  javascript git:(master) cat ~/.tern-project
{
  "ecmaVersion": 6,
  "libs": [
    "browser"
  ],
  "loadEagerly": [
  ],
  "dontLoad": [
  ],
  "plugins": {
    "es_modules": {},
    "node": {},
    "doc_comment": {
      "fullDocs": true,
      "strong": true
    }
  }
}
➜  javascript git:(master) pwd
/Users/apple/.vim/plugged/completor.vim/pythonx/completers/javascript
➜  javascript git:(master) which node
/usr/local/bin/node
➜  javascript git:(master)
```

trying

```
var name = {
  a: 1, b: 2
}


name.| (does not work here)
````

**Comment by rowanu** [comment]
I'm also seeing this, and haven't yet worked out the issue.

Any suggestions/hints for debugging completor + tern?

**Comment by aliev** [comment]
@rowanu the problem was "javascript.jsx" filetype for me, work only for :set ft=javascript.

**Comment by rowanu** [comment]
Thanks for the update, must be something wrong with my setup.

**Comment by rowanu** [comment]
Ah, my problem was my Tern config...

I think this issue can be closed and filed under "user error" 😛

**Comment by spencercwood** [comment]
So tern with YCM works with `javascript.jsx`. Is this a tern problem or a completer problem? The popular pangloss javascript package sets the `javascript.jsx` file type, do we add a fix for that here? happy to help with a pr

**Comment by scwood** [comment]
So tern with YCM works with javascript.jsx. Is this a tern problem or a completer problem? The popular pangloss javascript package sets the javascript.jsx file type, do we add a fix for that here? happy to help with a pr
