### ISSUE TITLE
 Code navigation

### ISSUE THREAD

**Issue by LambdaHJ** [maralla/completor.vim#107]
is it any possible to add jumping around and exploring code like youcompleteme?

**Comment by airhuman** [comment]
同问，能技术GoToDefinition, GoToDeclaration吗？

**Comment by maralla** [comment]
You can call the function `completor#do('definition')` to jump to definition. Add the following map to  use `<c-d>` as the trigger:
```vim
noremap <c-d> :call completor#do('definition')<CR>
```

**Comment by airhuman** [comment]
多谢！

**Comment by livc** [comment]
Look like it doesn't support jump to Declaration?
How to jump like `nnoremap <leader>gg :YcmCompleter GoToDefinitionElseDeclaration<CR>` in youcompleteme?

Thanks.
