### ISSUE TITLE
error in completing python

### ISSUE THREAD

**Issue by junhyeokahn** [maralla/completor.vim#111]
Hi,
First of all, I appreciate this great plugin.
I could do c family files completion.
Then I installed jedi and specify the path in anaconda and try some,
```variable.```
Once I type dot(.) it generate,
<img width="635" alt="screen shot 2017-06-03 at 6 18 57 pm" src="https://cloud.githubusercontent.com/assets/23005104/26757664/28d4d072-4889-11e7-8d45-1a2a3ff52cf1.png">

I would appreciate if you could help me

**Comment by junhyeokahn** [comment]
Addition to that, I am pretty sure it is related to version problem.
Because when I run python in command line,
I could do 
```
import jedi 
```
In my command line I am using anaconda python.
However, in vim, when I do 
```
:py import jedi
```
it return there is no module like that.

**Comment by vimalk78** [comment]
@junhyeokahn did it work for you in vim8 ?
i am trying, sometimes completion for numpy installed in anaconda2 works, most of the times it doesnt

**Comment by junhyeokahn** [comment]
@vimalk78 Hi, Yes it works for me.
If you use virtual environment, you would set in your configuration file as below.
```
let g:completor_python_binary='python'
```
