### ISSUE TITLE
ch_sendraw() write failed error with completion

### ISSUE THREAD

**Issue by wtheisen** [maralla/completor.vim#118]
Whenever I try and complete from something not in the file, I get a ch_sendraw() write failure. However basic completion from within the file works fine. I've been specifically testing this with python. Jedi is installed, and testing jedi_python in the completor install files manually works fine.

More specifically:

Error detected while processing function <SNR>125_complete[7]..completor#do_complete[5]..completor#daemon#process[25]..277:
line    1:
E631: ch_sendraw(): write failed

The top error happens once, the first time I attempt it and then the ch_sendraw() happens on every character I input. Thanks for your time!

**Comment by vimalk78** [comment]
same error happens for me also

**Comment by joaoh82** [comment]
Getting the same here! Need help!

**Comment by vimalk78** [comment]
i switched to neovim, so no more this error.

**Comment by maralla** [comment]
The commit a10228d74ef1594a8ab41258141b5ab691b5be05 may fix the problem. Please upgrade and give it a try.

**Comment by wtheisen** [comment]
It's working now, thank you!
