### ISSUE TITLE
Words getting auto-backspaced

### ISSUE THREAD

**Issue by notpratheek** [maralla/completor.vim#130]
Hello ! 

There seems to be bug, where in as the word is typed, it automatically is cleared out, and the pop-up menu then comes up.

Seems like, @RanchoCooper has fixed it. The reference is linked below. 

https://github.com/RanchoCooper/completor.vim/blob/462e5248ffeca94d3b033ed93740d0ced2e01dfe/autoload/completor/action.vim#L51

Could this be added into your main version of the plugin ? (which is the upstream)

Thanks in advance !

**Comment by maralla** [comment]
That's because of the `longest` option in `completeopt`. There has no longest common text of the matches so nothing inserted. You can add the config to your *vimrc*:
```vim
set completeopt-=longest
```

**Comment by notpratheek** [comment]
That seems to have fixed it ! Will close the issue now !

Thanks for the great plugin ! 👍

**Comment by hanqing0521** [comment]
I  also have this problem not only backspace a **word** but also **the whole line**. I have followed your suggestion 
```vim
set completeopt -=longest
```
