### ISSUE TITLE
since recently: automatic completion, not only suggestion

### ISSUE THREAD

**Issue by thet** [maralla/completor.vim#133]
since recently completor completes words i write automatically. e.g. in python, if i type ``impo`` it automatically expands it to ``import``. I'd prefer manual selection of a suggested completion-word.

But not only that, if I type ``te`` in vim script, completor offers me ``text``, ``textwidth`` but also deletes the ``te`` I've written in the vimscript buffer.

temporarily I fixed this with:
```
let g:completor_auto_trigger = 0
```

**Comment by maralla** [comment]
This commit 2f73dfe will fix the problem. Please update.

**Comment by thet** [comment]
Thanks, works!
