### ISSUE TITLE
Completion popup always flickers

### ISSUE THREAD

**Issue by jeromedalbert** [maralla/completor.vim#137]
### Steps to reproduce:

1. Create a `minimal.vim` file with the following content:

    ```
    call plug#begin('~/.vim/plugged')
    Plug 'maralla/completor.vim'
    call plug#end()
    ```

2. Run `nvim -u minimal.vim` with Neovim v0.2.1
3. Type some text that triggers the completion popup

### Actual behavior

The popup flickers whenever I type a letter:

![tenderloin3](https://user-images.githubusercontent.com/236461/30041461-32376f94-919f-11e7-8969-337c14159e61.gif)

### Expected behavior

The popup should not flicker.

Any idea why this is happening to me?

**Comment by maralla** [comment]
The popup always flickers because whenever a letter is typed the popup is closed by vim and then opened by completor. Completor tries to always get the fresh completion list. There is a way to improve the problem with the latest commit:
```vim
let g:completor_refresh_always = 0
```
After this config added to your vimrc the popup will not be refreshed if there are completion candidates prefixed by the letters you typed.

**Comment by jeromedalbert** [comment]
Ok, I thought it was a problem on my side, because the popup on the Readme GIF doesn't flicker, but after looking at it more closely there is no real letter typing happening there. So I'm closing the issue.

I tried `let g:completor_refresh_always = 0` with the same scenario in the GIF above, but it still flickers even though there is a completion candidate with the letters I typed.

**Comment by maralla** [comment]
I push a commit to fix the config. It will not flicker if you set `let g:completor_refresh_always = 0` now.

**Comment by jeromedalbert** [comment]
Great, thanks!

**Comment by jeromedalbert** [comment]
Works well for buffer completion. Filename completion still flickers (minor)
