### ISSUE TITLE
Options to enable/disable autocompletion for some filetypes

### ISSUE THREAD

**Issue by maln0ir** [maralla/completor.vim#14]
Currently autocompletion is enabled in all buffers. This is useful for coding, but not really necessary when you write prose, or use plugins like Unite.
There should be option to enable (or to disable) autocompletion only for some filetypes.

**Comment by maralla** [comment]
Now you can use these options to disable completions for files:
```
g:completor_blacklist
g:completor_whitelist
g:completor_filesize_limit
```
For more informations `h: completor-options`.

**Comment by maln0ir** [comment]
Thanks!
Unfortunately, blacklisting seems to not work for me. I wanted to disable completion for `markdown` filetype, so I configured blacklist like this:

    let g:completor_blacklist = ['markdown']

in my vimrc and autocompletion still works. I noticed that, for some reason, `g:blacklist` list contains only default values.

Tested on Vim 8.0.46 and commit 1dfb2c92.

**Comment by maralla** [comment]
Have you tried the latest commit?

**Comment by maln0ir** [comment]
Hi,
I pulled the latest version and it seems to work now. Thanks!
