### ISSUE TITLE
Add support to view docstring in pop-up window and goto definitions(Python)

### ISSUE THREAD

**Issue by hiteshpaul** [maralla/completor.vim#145]
I have recently switched from vim-jedi to completor. Its super fast and stable(especially for completions like tensorflow and numpy), but I miss some features from vim-jedi(or maybe its there but I am not aware of!)

First, the ability to view docstring when pressing "K"
Second, the ability to jump to definitions using <Leader>g

Are there any plans on implementing these features? or maybe some workarounds/hacks?

**Comment by maralla** [comment]
You can call the function `completor#do('definition')` to jump to definition. If the definition can be found it will be open in the current window. Here is an example key mapping for using control-d as the trigger:
```vim
noremap <c-d> :call completor#do('definition')<CR>
```

**Comment by maralla** [comment]
The ability to view docstring is planned.

**Comment by maralla** [comment]
Now you can call the function `completor#do('doc')` to view docstrings. Here is the key mapping settings for using `K`:
```vim
noremap <s-k> :call completor#do('doc')<CR>
```

**Comment by hiteshpaul** [comment]
Thanks @maralla !  That worked for me. 

This completely removes the dependency of `davidhalter/jedi-vim` from my vimrc and I can use completor for all my tasks related to completions.

**Comment by tuyenpm9** [comment]
I can't jump to definition, is definition must be in same current buffer? Don't know what did I miss.

**Comment by zjyExcelsior** [comment]
`import time` 和 `import datetime` 无效，`:call completor#do('definition')` 命令跳转不过去。@maralla
