### ISSUE TITLE
Not up-to-date items on buffer

### ISSUE THREAD

**Issue by tuyenpm9** [maralla/completor.vim#147]
> roll_again
>roll_fdsa
>roll_addd

somehow I can only get two of them in poplist that should be three.  
happen with python file.

**Comment by maralla** [comment]
I tested with these words in my environment, but it worked very well:

![demo](https://i.imgur.com/AQ1fXZR.gif)

**Comment by maralla** [comment]
Can you please disable all plugins exclude completor.vim and try it again?

**Comment by tuyenpm9** [comment]
Still persist the issue with only completor enabled:
https://imgur.com/gSQ56j6

It happend with python file only I noticed, I use gvim on windows 10 downloaded from here: https://bintray.com/micbou/generic/vim

**Comment by tuyenpm9** [comment]
I open a new py file and it works as expected, but with existing files (maybe before completor installed - I don't think it's problem just list) the issue happened. Will Completor re-scan current buffer for each time it opened or editing?

**Comment by maralla** [comment]
I tried one more and I think I produced what you have encountered:
```python
roll_again = 3

roll_aaa
roll_ddd
roll_ddd


roll|  # cursor here, only `roll_again roll_again = 3` in popup list
```

This happens because `jedi` has the higher priority to supply the completions candidates and `jedi` only supplies the `roll_again` so the other `roll_*` are not shown. If you type `r_` all candidates should be shown.

**Comment by tuyenpm9** [comment]
Do you have workaround solution or it's just fine behavior?

**Comment by maralla** [comment]
I think it's better to make semantic and buffer completion result both show on the popup list. So when I have enough time I'll try to improve it.

**Comment by tuyenpm9** [comment]
Thank you, looking forward to it. I'm learning python from scratch, 'll give you a hand if possible.
