### ISSUE TITLE
use neosnippet many Completion list

### ISSUE THREAD

**Issue by dohq** [maralla/completor.vim#149]
I am sorry for my poor English. 

I use completor and neosnippet
but one expand neosnippet many Completionlist

use this vimrc

```
let $DOTVIM = expand($VIM.'\vimfiles')

call plug#begin($DOTVIM.'/plugins')
Plug 'maralla/completor.vim'
  Plug 'maralla/completor-neosnippet'
Plug 'Shougo/neosnippet'
  Plug 'Shougo/neosnippet-snippets'
call plug#end()
filetype plugin indent on

" NeoSnipet {{{
"Plugin key-mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)
"}}}
```

gif
![neosnippet](https://user-images.githubusercontent.com/1639089/31753546-431f2806-b4cc-11e7-8a0b-278c04704213.gif)

Regards,

**Comment by maralla** [comment]
Thanks for reporting! I pushed a commit maralla/completor-neosnippet@6cd015ddf2d0421859edb66c6ae4f71c89db6b34 to fix the problem. Please update completor-neosnippet and try again.

**Comment by dohq** [comment]
Thanks fix this !
I update and fix confirm

Than kyou!
