### ISSUE TITLE
Improvement for docs window

### ISSUE THREAD

**Issue by gasabr** [maralla/completor.vim#153]
First of all, thank you for such an amazing tool!

I have a little suggestion for docs window, which pops up sometimes on the top of the screen. It's super useful, but is it possible **to keep the line being edited in the same position on the screen** as it was before the window popped up? The problem is, after the docs window is closed I have to search for the place I was typing and this makes the process a bit annoying.

I know almost nothing about vim script, but from the user experience point of view here are my thoughts on how it could be done "better": 

1. Overlap the lines below the pop up window, if possible.
2. Separate window for docs (split the screen and toggle it when needed as nerdtree or tagbar)

**Comment by maralla** [comment]
Thanks for reporting! Do you mean the preview window:

![com](https://user-images.githubusercontent.com/2238118/31923110-8e4319a8-b83e-11e7-8dbb-ab44a55c4a72.gif)

The preview window which contains the docs should not change the cursor position normally.

**Comment by gasabr** [comment]
What you showed is the perfect behaviour I was thinking about, but in my case docs window appears to be on top of the editor. What should I do to move to the bottom?

![25](https://user-images.githubusercontent.com/10960369/31989515-2d7d9132-b97b-11e7-94a2-bb7883ce6047.gif)

**Comment by maralla** [comment]
You can add this settings to your vimrc:
```vim
set splitbelow
```

**Comment by gasabr** [comment]
Thank you for the tip! And sorry for stupid question.

**Comment by tuyenpm9** [comment]
@maralla, @gasabr  : Does completor bundled with docs?

**Comment by tuyenpm9** [comment]
How to keep doc windows and how to resize it, I try to read it but it destroyed when I click on. I doubt it's expected behavior. So how to resize it?

**Comment by maralla** [comment]
The doc window will be closed after completion finished by default. You can add the following config to make the doc window keep open after finished:
```vim
let g:completor_auto_close_doc = 0
```

The doc window is a vim feature. You can switch to the doc window and use `<Ctrl-W> +/-` to increase/decrease height. You can use the config `set &previewheight = 12` to set the default height of the doc window.

**Comment by tuyenpm9** [comment]
I thought it was `echodoc` plugin, if not how to disable doc window so `echodoc` will print only function prototype?

**Comment by tuyenpm9** [comment]
Oh, I have the answer.
