### ISSUE TITLE
filename completion improvement

### ISSUE THREAD

**Issue by cvlmtg** [maralla/completor.vim#155]
Hi, would it be possibile to make filename completion a bit smarter when the text begins with `</` ? every time I write some html / jsx I get filename completions when I just want to close a tag.

<img width="414" alt="schermata 2017-11-04 alle 12 16 11" src="https://user-images.githubusercontent.com/6401008/32404897-6c2e3a30-c15a-11e7-9fa6-0c4a7706c600.png">

Thanks for the plugin, it gets better every time!

**Comment by maralla** [comment]
The problem should be fixed in commit a8d0f787ffe0cb7afdd18f6e5fd79dfdf7bacf8c.

**Comment by cvlmtg** [comment]
thanks!
