### ISSUE TITLE
Any plan to support Java with artur-shaik/vim-javacomplete2?

### ISSUE THREAD

**Issue by J-Liu** [maralla/completor.vim#157]
completor.vim is the best completion plugin I ever use, it help me delete Pycharm from my computer, and I wanna delete Idea too, eagerly.
I don't like the `project` stuffs, so I refuse any IDE in my mind, deeply.
Is there any plan to support Java officially?  Or something such as cooperate with `artur-shaik/vim-javacomplete2`?

**Comment by wsdjeg** [comment]
@J-Liu compltor support omni-func completion, and javacomplete2 is just an omni plugin for java, you should add:

```
let g:completor_{filetype}_omni_trigger = '<python regex>'
```
to your config.

**Comment by J-Liu** [comment]
@wsdjeg Thank you.
But I am not sure about how to write the proper regex.
Does it complete from JDK and the packages in the same project?

**Comment by wsdjeg** [comment]
```
let g:deoplete#omni#input_patterns.java = get(g:deoplete#omni#input_patterns, 'java', [
      \'[^. \t0-9]\.\w*',
      \'[^. \t0-9]\->\w*',
      \'[^. \t0-9]\::\w*',
      \])
```

I use deoplete by default, but I also include this plugin to SpaceVim, for deoplete I use config above, and I do not know if ocmpletor support list as the value.

**Comment by wsdjeg** [comment]
you can have a try:

```
let g:completor_java_omni_trigger = '[^. \t0-9]\.\w*'
```

**Comment by J-Liu** [comment]
‘[^. \t0-9]\.\w*’ will work but not that good as javacomplete2.
SpaceVim make me not very comfortable, I won't use it.

**Comment by wsdjeg** [comment]
In this issue do I recommand you to use SpaceVim? well just do what you want

**Comment by Shadowsith** [comment]
let g:completor_java_omni_trigger = '([$\w]{1,}|\.[$\w]*)$' does do the trick for me and works with packages as well if javacomplete2 is installed correctly.
