### ISSUE TITLE
Hook up Ultisnips Triggers to the completion popup 

### ISSUE THREAD

**Issue by josefson** [maralla/completor.vim#16]
It would be a killer feature if one could have the ultisnips triggers shown at the completion popup, i think youcompleteme does that. But this is so lightweight i would rather use it here.
I mean, one could still use ultisnips w/o being shown the possible triggers, but i got so used to it being shown to me and i created a bunch of custom ones for different cases, which now makes it difficult for me to have it all in my head.

Well, i hope it can be integrated one day. Thanks for your already amazing plugin tho.

**Comment by maralla** [comment]
Now ultisnips triggers completion can be used. Implemented in #18.

**Comment by josefson** [comment]
I'm gonna close it, just updated and it is working great. Thank you!
