### ISSUE TITLE
How to enable javascript completion

### ISSUE THREAD

**Issue by devinalvaro** [maralla/completor.vim#160]
Don't get me wrong, I've read the instruction, but it's still not clear enough. The instruction says to run `make js`, but I don't understand where to run `make js`. As for the `g:completor_node_binary`, is global binary of node e.g. `/usr/bin/node` okay? And lastly, can I use this with a global installation of tern, e.g. `sudo npm -g install tern`?

Sorry if this is a stupid question, I'm new to doing JavaScript projects. Thank you!

**Comment by devinalvaro** [comment]
So suddenly I dawned on me to run `make js` in completor.vim directory, and it worked. Thanks, perhaps the instruction could be made clearer for unexperienced users.

**Comment by onlyanegg** [comment]
Agree on this. It would be nice to reopen this issue as a documentation enhancement.
