### ISSUE TITLE
g:completor_select_first

### ISSUE THREAD

**Issue by dNitro** [maralla/completor.vim#163]
Could we have an option, if set to `True`, the first item will became always selected.
This way the first item is always in focus(highlighted) and also we could select the matched item without extra mapping of `Tab` or `Return` keys and just by hitting them.

**Comment by maralla** [comment]
You can update completor to the latest commit and use the following config to select the first item automatically:
```vim
let g:completor_set_options = 0
set cot=preview,menuone
```

**Comment by dNitro** [comment]
Tanx. Of course i also add `noinsert` to `completeopt` option and the result is exactly the desired one:
```vim
let g:completor_set_options = 0
set cot=preview,menuone,noinsert
```
