### ISSUE TITLE
add support for `.clang`

### ISSUE THREAD

**Issue by wsdjeg** [maralla/completor.vim#164]
hi @maralla 

I just use your plugin in spacevim (https://github.com/SpaceVim/SpaceVim/pull/1025)

and I just found the deoplete-clang2 plugin use a `.clang` file as the complete flags, as I know clang is not only a tools for completion, so I think support `.clang` file will be better.

**Comment by maralla** [comment]
Thanks! I pushed a [commit](ad4604e991f3cdab4f0518b1fd90974b386fec2f) to add the `.clang` file.

**Comment by wsdjeg** [comment]
nice work， Thanks！
