### ISSUE TITLE
[Rust] Feature to preview doc in rust

### ISSUE THREAD

**Issue by hiteshpaul** [maralla/completor.vim#166]
Hi @maralla , 
Is there a feature to support preview of docs in rust, similar to [this](https://github.com/racer-rust/vim-racer#example-mappings)? 

It is similar to this issue which I had raised earlier #145 . Any support will be greatly appreciated!

**Comment by maralla** [comment]
The preview doc for rust is implemented in the commit 38133224e76a965bec2872505eed4904a8c7f2b7. Please update.

**Comment by hiteshpaul** [comment]
Thanks for the help, closing this.
