### ISSUE TITLE
Open doc buffer at the bottom, jumping line

### ISSUE THREAD

**Issue by JPFrancoia** [maralla/completor.vim#167]
Hi,

I have been using completor for a few months now, and I think it's (almost) perfect. I had been looking for a completion tool for ages, but I found nothing as simple and efficient as completor.

However, a few points could be improved (but maybe there is already a solution):

- If I open a python file, and when completor completes a function call, the doc buffer (where the docstring of the function is displayed) is opened on a buffer above the current one. Can I choose where this buffer is opened, at the bottom of the screen for example ?

- If I open a python file, and when completor completes a function call, the doc buffer (where the docstring of the function is displayed) is opened on a buffer above the current one. Opening this buffer "moves" the current line down, to give space to the top buffer. Would there be a way to avoid that ? It takes time to re-focus on the right line. It would be nice to open the top buffer without pushing the bottom one down.

Cheers

**Comment by maralla** [comment]
You can use the config `set splitbelow` to place the doc buffer at the bottom.

**Comment by JPFrancoia** [comment]
Sorry for the delay.

Thanks for the tip. Rests the second issue, which is a bit annoying.
