### ISSUE TITLE
add option to disable quickfix window

### ISSUE THREAD

**Issue by vitiral** [maralla/completor.vim#169]
I like the autodoc feature, but I find the quickfix window annoying. Is there any way to disable it?

Thanks for the great plugin!

**Comment by maralla** [comment]
You can put the following config to your vimrc:
```vim
set cot-=preview
```

**Comment by vitiral** [comment]
that worked!

**Comment by tuyenpm9** [comment]
`quickfix`'s a vim's feature, not related to completor.

**Comment by vitiral** [comment]
I know, but it seemed like completor was opening it. Obviously it was the completion options themselves but I was having trouble finding how to disable it.
