### ISSUE TITLE
Open function definition in a new split/buffer/tab

### ISSUE THREAD

**Issue by imaluengo** [maralla/completor.vim#170]
Sorry I'm a bit new here. I am aware that one could jump to the definition as stated in https://github.com/maralla/completor.vim/issues/145

Is there an option to open the definition in e.g. a new horizontal split rather than in the same window?
 
I'm currently using:
```
noremap <C-d> :split \| call completor#do('definition')<CR>
```

But I wonder if there is any other better alternative? Or is it the way to go?

**Comment by Carpetsmoker** [comment]
There is a `g:completor_def_split` option that can be set to `split`, `vsplit`, or `tab`. See #208 and #218
