### ISSUE TITLE
Completor requires vim compiled with python or python3 and has features `job`, `timers` and `lambda`

### ISSUE THREAD

**Issue by zhuweiyou** [maralla/completor.vim#177]
How to fixed it ?

**Comment by xiaosong0911** [comment]
If you are using vim8 under windows, then you should install python and make sure python can be called from vim.

**Comment by zhuweiyou** [comment]
mac

**Comment by Shougo** [comment]
You should check it by `:echo has('python')` and `:echo has('python3')`

**Comment by zhuweiyou** [comment]
![image](https://user-images.githubusercontent.com/8413791/36366235-24261d3e-1588-11e8-8362-069c4cb4263b.png)

**Comment by Shougo** [comment]
Please execute `:echo has('python')` and `:echo has('python3')` in your Vim.

**Comment by Shougo** [comment]
And what is your Vim version?

**Comment by Shougo** [comment]
The check is here.  I think your Vim is too old or if_python and if_python3 are not enabled.

https://github.com/maralla/completor.vim/blob/master/plugin/completor.vim#L12

**Comment by zhuweiyou** [comment]
vim 8.0.1400

```
:echo has('python') // 1
:echo has('python3') // 0
```

**Comment by Shougo** [comment]
Please execute `:echo Check()`

```vim
function! Check()
  return ((has('python') || has('python3'))
        \ && has('job') && has('timers') && has('lambda')) || has('nvim')
endfunction
```

**Comment by zhuweiyou** [comment]
```bash
:echo (has('python') || has('python3')) && has('job') && has('timers') && has('lambda')) || has('nvim') // 1
```

**Comment by Shougo** [comment]
I don't know why it does not work...

**Comment by Shougo** [comment]
You can add `:echomsg s:has_features()` in L15.

https://github.com/maralla/completor.vim/blob/master/plugin/completor.vim#L15

**Comment by zhuweiyou** [comment]
Open some files will report this warning, not all

**Comment by maralla** [comment]
What is the output of `vim --version`?

**Comment by xclidongbo** [comment]
me too . How can I fix it?

**Comment by indrabinridwan** [comment]
yeah, i have the same problem

**Comment by maralla** [comment]
@indrabinridwan  Please post the result of `vim --version` here.

**Comment by yan-ace62** [comment]
@indrabinridwan  if you input vim `--version |grep python` and result is  `-python  -python3 ` , then You should turn on VIM to support python. You will find that the problem has been solved.  How to turn on VIM to support pythom?, see [](https://vi.stackexchange.com/questions/10242/vim-8-0-python-support)

**Comment by caixxiong** [comment]
firstly, confirm your vim support python: vim --version | grep python, must +python and +python3
secondly, confirm python is available in vim:  :echo has("python"),  :echo has("python3"), must return 1
thirdly, you may be to confirm jedi is installed by pip or pip3, and make sure it be consistent with your available python in vim

**Comment by SpecialAmir** [comment]
apt install vim-python
