### ISSUE TITLE
how to make completor.vim autocomplete  hidden files?

### ISSUE THREAD

**Issue by pittcat** [maralla/completor.vim#182]
If making vim complete  hidden files,I have to press c-x c-f to trigger .but I think there should be a
better way to solve it.

**Comment by maralla** [comment]
The commits a9bf30db4114491535366b06389acde7a5a183c1 and aeaff289470de364fd154cd0eca4ecbea01dd1d6 enabled the support to complete hidden files. Please update.

**Comment by pittcat** [comment]
nice work

**Comment by pittcat** [comment]
it seems like that something wrong.
![pushd](https://user-images.githubusercontent.com/22888402/36730709-5e89a758-1c03-11e8-88fe-3714ad1ad26b.gif)

**Comment by maralla** [comment]
The latest commits fixed the problem. Please update.

**Comment by pittcat** [comment]
It works well.Thank you.

**Comment by Shougo** [comment]
I think it should be closed.
