### ISSUE TITLE
Status bar flashes "^X mode (^]^D^E^F^I^K^L^N^O^Ps^U^V^Y" and completion popup doesn't show in JavaScript files

### ISSUE THREAD

**Issue by scwood** [maralla/completor.vim#188]
.vimrc:

```
call plug#begin()
Plug 'maralla/completor.vim'
call plug#end()
```

I've tried reinstalling vim. Any ideas?

**Comment by Shougo** [comment]
You can disable the status bar flash by `set shortmess+=c`.

**Comment by scwood** [comment]
That disabled the status bar flash... but the completion still isn't triggering. Nothing is happening. Plugin is up to date

**Comment by maralla** [comment]
Have you ran make js under the completor.vim root?

**Comment by Shougo** [comment]
https://github.com/maralla/completor.vim/blob/master/pythonx/completers/javascript/__init__.py

I think node binary is needed.

**Comment by scwood** [comment]
Ahh, that's it... thanks for the quick replies. Been a while since I set this up on a new machine.
