### ISSUE TITLE
"E117: Unknown function: ch_canread..." error when editing .c/c++ files

### ISSUE THREAD

**Issue by jplrssn** [maralla/completor.vim#189]
Hello,

I'm getting the following error when typing in insert mode (the error message appears after almost every keypress) in Vim 8.0. It only seems to happen when editing c/c++ files.

```
E117: Unknown function: ch_canread
E15: Invalid expression: ch_status(a:ch) ==# 'buffered' && ch_canread(a:ch)
```

**Comment by maralla** [comment]
Please update your vim to the latest version.

**Comment by jplrssn** [comment]
D'oh! Updating from 8.0.5 to 8.0.1587 did the trick - thanks! 🍺
