### ISSUE TITLE
Disable file and buffer completers

### ISSUE THREAD

**Issue by fatih** [maralla/completor.vim#19]
There is no way to disable these fallback completers. It slows down Vim for large files because it tries to complete for every single word. We should make them optional or provide a setting to disable it.

**Comment by fatih** [comment]
These settings are a good start, thanks @maralla . But how do I disable file completion, such as `/etc/...` and buffer completion? These setting doesn't allow them ?

**Comment by maralla** [comment]
More options are added for disabling specific completer:
```
g:completor_disable_filename
g:completor_disable_buffer
g:completor_disable_ultisnips
```

**Comment by fatih** [comment]
Thanks a lot @maralla 👍
