### ISSUE TITLE
"//" locks up comments in cygwin

### ISSUE THREAD

**Issue by squeezyphresh** [maralla/completor.vim#192]
Any time I try and type a comment with "//" in any type of file, file path completion tries to complete a windows network share path (e.g. "//foo/bar/remote_file.txt"), causing my whole editor to freeze while it tries to complete the path, probably because I'm using vim in an environment with tons of network paths. Is it possible to turn on file path completion?

Just in case it matters, I'm running in cygwin, on Windows 7, terminal vim.

**Comment by ErichDonGubler** [comment]
I getting this issue too on Windows 10 using MSYS2's installation of `vim` and `vim-plug` to use this plugin without additional configuration.

If you need, I can make a minimum reproducible example -- it wouldn't be hard. :)

**Comment by ErichDonGubler** [comment]
I was able to resolve this with this current configuration in my `.vimrc`:

```viml
" Completion
if has('python')
	Plug 'maralla/completor.vim'
	if has('win32unix')
		let g:completor_disable_filename = 1
	endif
endif
```

**Comment by squeezyphresh** [comment]
This resolved my issue as well, but it's a shame you have to disable filename completion completely

**Comment by ErichDonGubler** [comment]
Yeah...hopefully we can get a config option to get a finer-grained blacklisting of the offending functionality!

**Comment by maralla** [comment]
I made a slightly improvement by ignoring `//` in the commit ef74ebcf934ebf6a68190cebcd3debce495aa481. Please update.
