### ISSUE TITLE
'@' in file path seems to break file completition

### ISSUE THREAD

**Issue by tomaskallup** [maralla/completor.vim#194]
I have a `@types` folder in my project, which contains typescript typings, if I try to import the file, completor leads me to the directory (first attached picture) once I select it, the completition breaks and thinks my path starts with `/` (second picture).

<img width="614" alt="screen shot 2018-04-04 at 13 51 56" src="https://user-images.githubusercontent.com/26621166/38306222-2415dc80-3810-11e8-8bd5-8a6ab86c1540.png">
<img width="854" alt="screen shot 2018-04-04 at 13 52 04" src="https://user-images.githubusercontent.com/26621166/38306226-2a1cf050-3810-11e8-8525-6d315e18bab1.png">

**Comment by maralla** [comment]
The commit 9ef09cf30c35f75c2a05c440e330fc8918ab72c9 fixed the problem. Please update.

**Comment by tomaskallup** [comment]
Perfect, thanks!
