### ISSUE TITLE
Docs preview window not showing

### ISSUE THREAD

**Issue by leighmcculloch** [maralla/completor.vim#199]
The autocompletor works amazing and displays a pop-up, but the docs preview window is not displaying when autocompleting. Is there an option that needs enabling to display the docs window?

**Comment by serge-rgb** [comment]
+1. I'm loving this plugin. My only problem so far is that the completion tooltip closes the  preview window for some reason.

**Comment by leighmcculloch** [comment]
If like to solve this but I'm a bit lost on where to start. @serge-rgb is you vimrc anywhere I could :eyes: to look for similarities with mine that might be the cause? I use vim-go and vim-auto-save and I wonder if it's one of those.

**Comment by serge-rgb** [comment]
Sure thing. I just made a [gist](https://gist.github.com/serge-rgb/cc2266d1e1e13412782493835e065f1b).

**Comment by maralla** [comment]
Some file type complete engine has no doc provided so the preview window not shown. Some file type like *python* do have the preview window, and the default behaviour is to closed the window when completion completed. If the file type support docs there has an option to make the preview window not close after completion `let g:completor_auto_close_doc = 0`.

**Comment by leighmcculloch** [comment]
@maralla I'm using this with Go, which as I understand supports the preview window, and the issue isn't that the preview window is closing too soon, my issue is it's not opening at all.

**Comment by leighmcculloch** [comment]
My vimrc is pretty small, this is it: https://github.com/leighmcculloch/vim_dotfiles/blob/24a75b1/vimrc

**Comment by maralla** [comment]
Please update to the latest commit which I just pushed to enable the preview window for Go.

**Comment by leighmcculloch** [comment]
@maralla Thanks, that was fast! I gave it a go with commit f99230f and the preview now opens, but the only information displayed in the preview is the declaration of the identifier. For example, for a function, only `func funcName(args) returnValue` is shown. The godoc for the function isn't shown.

**Comment by leighmcculloch** [comment]
@maralla Do I need to install a another tool other than `gocode` to get the actual godoc text?

**Comment by maralla** [comment]
Godoc is current not supported by completor. Completor only uses gocode for completion and the content of preview window is provided by gocode not godoc. But the support for godoc is planned.

**Comment by leighmcculloch** [comment]
If nobody is already working on adding support for godoc I'd like to take a stab at it.

**Comment by leighmcculloch** [comment]
@maralla I took a stab at it, see #202. I've got it working, but I need some guidance on how to improve the solution.
