### ISSUE TITLE
breaks C-e

### ISSUE THREAD

**Issue by justrajdeep** [maralla/completor.vim#20]
Hi 

When i want to populate a line from below using `C-e` and the completion popup window is open it does not copy the text from below.

Thanks

**Comment by xtal8** [comment]
Hi,
as a temporary fix you could use the following mapping:
```
inoremap <expr> <C-e> pumvisible() ? "\<C-y>\<C-e>" : "\<C-e>"
```

**Comment by maralla** [comment]
Now `CTRL-E` and `CTRL-Y` have the same meaning as `:h complete_CTRL-E` and `:h complete_CTRL-Y`.
