### ISSUE TITLE
No completion refresh since commit 1b088

### ISSUE THREAD

**Issue by soywod** [maralla/completor.vim#200]
Since last commit, when I type the `.` character, I get all completion in the popup, but when I continue to type, the popup does not refresh anymore. It refreshes only when I delete a character. I rolled back to previous commit and no problem anymore. Any idea ?

I tried in a TypeScript file, after accessing a object property (but this problem seems to be general)

**Comment by maralla** [comment]
Is this config `g:completor_refresh_always` set to `0` in your `vimrc`?

**Comment by soywod** [comment]
Not, it's at `1`. Well, I noticed that it's even the case with previous commit. Here a screen : 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10437171/40046945-6d058632-582e-11e8-89ad-c7113fc41910.gif)

The completion is good, but it's doesn't refresh when I type, only when I delete characters. Any idea ?

**Comment by maralla** [comment]
Have you installed the latest version of https://github.com/maralla/completor-typescript?

I just tested in my environment without any special config and it worked very well:

![demo](https://i.imgur.com/LNc8CmO.gif)

**Comment by soywod** [comment]
It works with your completor-typescript plugin, but not without. Thank you, I close the issue.
