### ISSUE TITLE
Error message on CompleteDone event in cmdline window

### ISSUE THREAD

**Issue by lifecrisis** [maralla/completor.vim#204]
Vim version 8.1.0034, latest version of completor as of this writing (0d4c6292).

To reproduce:

1. Open cmdline window with `q:` normal mode command.
2. Type a letter, use `<C-N>` to begin completion.
3. Type `<ESC>` to end completion.
4. Observe the error message.

This is due to the fact that `:pclose` can't be called in the command line window.  Thus, the autocommand for the `CompleteDone` event fails.

**Comment by maralla** [comment]
Thanks for reporting. The commit b7d19ac80bac0eceb2482c6c9f7226c043418e70 fixed the problem.

**Comment by lifecrisis** [comment]
@maralla: looks great. I updated my installation and the bug was fixed on my end. Thanks for the rapid response!
