### ISSUE TITLE
`set cot-=preview` can not disable autodoc

### ISSUE THREAD

**Issue by TeYoMe** [maralla/completor.vim#212]
os: win10, python3.6,vim8.1

我在vimrc 中添加了 `set cot-=preview` 设置，但是在补全python时，文档窗口在某些情况下仍然会自动弹出
比如，输入 `imp` 然后按 <tab>键补全时，文档窗口会自动弹出
下面是我`vimrc`中相应的设置
```
let g:completor_python_binary = 'C:\Users\Huang\Envs\django\Scripts\python'
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"

set cot-=preview
```
请问应该怎么设置才能禁止文档窗口自动弹出
或者能否增加一个按键映射，比如，按 `K` 键时激活文档窗口的功能

**Comment by maralla** [comment]
https://github.com/maralla/completor.vim/blob/master/README.md#complete-options-completeopt

**Comment by TeYoMe** [comment]
`let g:completor_complete_options = 'menuone,noselect,preview'` 我加上了这个设置，但是还是不行，而且我还在另一台ubuntu的机器上进行测试，结果还是一样~~

**Comment by maralla** [comment]
@TeYoMe `let g:completor_complete_options='menuone,noselect`

**Comment by TeYoMe** [comment]
@maralla 可以了，谢谢！
