### ISSUE TITLE
Question: don't understand how to allow dictionnary completions..

### ISSUE THREAD

**Issue by mahaaaham** [maralla/completor.vim#221]
Hi,

  I'm not sure I'm in the good place for this, but I just don't undertand how to use completor in my case:

I have made dictionnary completion with the file format .sage, so, il my **ftplugin/sage.vim**, I set

 20  set dictionary+= \~/.vim/dictionaries/sage
 21 set complete+=k,.

This work when I put **CTRL-X CTRL-K** but I would be happy if this completion was displayed when I write, so, compatible with the completor plugin.

I have read the paragraph **other language** but, sincerely, and with some reseach, I still don't get it...

Sorry to put this as an issue, but I didn't know where I could ask this.
Thanks for your help!

(by the way, surely no link with this, but strangely, when I use **CTRL-N** , not all words in the dictionnary are properly complety, even if it's working well with **CTRL-X CTRL-K** )

**Comment by maralla** [comment]
Autocomplete for dictionary is not supported by completor currently and I don't have much spare time to implement this feature. Contributions are welcome.

**Comment by mahaaaham** [comment]
Thanks a lot!
