### ISSUE TITLE
Does not work on Mac with Vim 8.0.1283 / 8.1.560

### ISSUE THREAD

**Issue by dschuessler** [maralla/completor.vim#237]
I can not get completor.vim to work on my Mac. No vimrc. Just the installation steps for the Vim package manager. Doesn't work with vim-plug either.

MacVim 8.1.560 (+python/dyn / +python3/dyn) on macOS 10.14.1 does not work.
System Vim 8.0.1283 (+python/dyn / -python3) on macOS 10.14.1 does not work.
Vim-nox 8.0.707 (-python / +python3) on Raspbian GNU/Linux 9.4 **does work**.

Setting `g:completor_debug` to 1 does not create the log file. I am at a loss and would appreciate help. Thank you!

**Comment by dschuessler** [comment]
I had to reinstall the OS and with it many command line tools. The problem is gone. I can not provide information about the initial cause.

**Comment by tpict** [comment]
I think a recent change must have caused the issue - I've just updated Completor and it's stopped working on my Mac. Doesn't create a log file. I was using it on a Linux machine yesterday and the latest version was fine with exactly the same vimrc.
