### ISSUE TITLE
Can you give me a trigger about omni trigger for php

### ISSUE THREAD

**Issue by markwu** [maralla/completor.vim#24]
I tried to figure it out, but no luck.

Would you please kindly give me an example about php omni trigger? 

Thanks.

**Comment by maralla** [comment]
I'm not familiar with php. Here is a trigger I composed:
```vim
let g:completor_php_omni_trigger = '([$\w]+|use\s*|->[$\w]*|::[$\w]*|implements\s*|extends\s*|class\s+[$\w]+|new\s*)$'
```

**Comment by markwu** [comment]
Wow, great thanks, the trigger works really really well. 

But, I meet the same problem as I described here https://github.com/Shougo/neocomplete.vim/issues/560#issuecomment-254551951.

It seems vim timer has some bugs, and the timer_stop not working.

I will try to capture a screencast for you.

Is that possible to disable the timer to avoid the problem?

**Comment by markwu** [comment]
I create a new issue https://github.com/maralla/completor.vim/issues/35 for time_stop problem, and I close this one. Thanks for your kindly help.
