### ISSUE TITLE
C++ - method suggestion completes with unwanted characters

### ISSUE THREAD

**Issue by milochadam** [maralla/completor.vim#246]
![image](https://user-images.githubusercontent.com/27895477/51806558-71f95c00-227b-11e9-915e-03dd7a15b4a4.png)

As you can see, besides name function (<#Postac &przeciwnik#>) is inserted.
Minimal .vimrc:

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
call plug#begin()
    Plug 'maralla/completor.vim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()            " required

filetype plugin indent on    " required
let g:completor_clang_binary = '/usr/bin/clang'
```

**Comment by DCsunset** [comment]
You can use the option
```
let g:completor_clang_disable_placeholders = 1
```
 to disable the insertion of placeholders.

**Comment by milochadam** [comment]
Oh, my bad. I somehow missed that in the docs and thought it was a bug.
Thank you, the issue can be closed.
