### ISSUE TITLE
Feature Request - LSP Support

### ISSUE THREAD

**Issue by ryanp97** [maralla/completor.vim#248]
Are there any plans in add LSP support into completor?

**Comment by prabirshrestha** [comment]
You could most likely easily create a source for [vim-lsp](https://github.com/prabirshrestha/vim-lsp).

Here are several ones for vim-lsp.

- https://github.com/prabirshrestha/asyncomplete-lsp.vim
- https://github.com/lighttiger2505/deoplete-vim-lsp
- https://github.com/ncm2/ncm2-vim-lsp

**Comment by maralla** [comment]
LSP support for completor is working in progress.

**Comment by maralla** [comment]
Now the feature is implement by #254.
