### ISSUE TITLE
Customized shortcut?

### ISSUE THREAD

**Issue by pluskid** [maralla/completor.vim#25]
Thanks for this plugin! Is it possible to customize the behavior of some keys? For example

- tab to complete from candidate list (and further tab to travel down)
- Enter to close the popup and do newline (instead of doing nothing)

**Comment by xtal8** [comment]
You can use these mappings:
```
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"
```

**Comment by leszekhanusz** [comment]
Those mappings are quite useful !
Maybe they should be set as the default ? Or at least be added to the documentation to be more visible.

**Comment by pluskid** [comment]
Thanks! Those works like a charm! +1 for adding them to README.md.

**Comment by maralla** [comment]
Now I added those mappings to [README.md](https://github.com/maralla/completor.vim#use-tab-to-select-completion).
