### ISSUE TITLE
自动补全的函数按Enter后，自动加入了参数项，干扰编程！

### ISSUE THREAD

**Issue by laoyouji007** [maralla/completor.vim#253]
写代码输入函数名的前几个字母后，出现函数提示，再按“Enter”键后，自动写以下格式的函数，但我不需要后面自动插入的这些参数，如<##>包起来的几个参数如何支掉，不要自动加入？
    
WebRtcNS32KSample(<#char *szFileIn#>, <#char *szFileOut#>, <#int nSample#>, <#int nMode#>)

**Comment by maralla** [comment]
添加如下配置到 *vimrc* 可以避免 placeholder：
```vim
let g:completor_clang_disable_placeholders = 1
```
