### ISSUE TITLE
Python补全结果改进

### ISSUE THREAD

**Issue by bstaint** [maralla/completor.vim#276]
比如补全requests.get的时候因为jedi会显示pyi内容所以结果不精确：

![master](https://user-images.githubusercontent.com/5853792/66806816-0c5d1500-ef5b-11e9-84cf-1325b8b1cc16.png)

可以改成：
```
    def on_complete(self):
        for c in self.script.completions():
            docs, desc = c.docstring(), c.description
            if not c.docstring():
                assigns = c.goto_assignments()
                if assigns:
                    docs, desc = assigns[-1].docstring(), assigns[-1].description

            yield {
                'word': c.name,
                'abbr': c.name_with_symbols,
                'menu': desc,
                'info': docs,
            }
```

![local](https://user-images.githubusercontent.com/5853792/66806950-44645800-ef5b-11e9-8dfd-c02666b3818f.png)

因为在使用echodoc.vim插件的时候会根据v:completed_item.info来获取参数列表

**Comment by maralla** [comment]
Thanks for reporting! Would you mind to submit a pr to address the problem?
