### ISSUE TITLE
Integrate ALE completion

### ISSUE THREAD

**Issue by BiochemLouis** [maralla/completor.vim#290]
ALE now offers [completion](https://github.com/dense-analysis/ale/blob/7ff87a942b8a6c2cf50b7cf34f9b98421508f542/doc/ale.txt#L373) that is integrated with [Deoplete](https://github.com/Shougo/deoplete.nvim) and [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim).

I tried asyncomplete.vim but quickly ran into the into the issue [asyncomplete.vim#195](https://github.com/prabirshrestha/asyncomplete.vim/issues/195)

Would it be possible to integrate ALE as a completion source ?

I know completor.vim has LSP support, but running two LSP instances is quite wasteful.

**Comment by maralla** [comment]
The PR #292 resolved the issue.

To use ALE as the completion source add the following config to your vimrc:

```vim
let g:completor_filetype_map = {}

" For example make javascript complete using ALE:
let g:completor_filetype_map.javascript = {'ft': 'ale'}
```

**Comment by polyzen** [comment]
Confirming that I can use ALE as a completion source.
