### ISSUE TITLE
filename completion

### ISSUE THREAD

**Issue by cvlmtg** [maralla/completor.vim#34]
would it be possible to make filename completion relative to file directory instead of current working directory? setting autochdir in vim breaks other things, so it isn't really an option.

thanks!

**Comment by maln0ir** [comment]
Filename completion works that way, but first you need to type `./` before filename. Then you can even go "up" in the directory tree without problems.

**Comment by cvlmtg** [comment]
no, it doesn't work that way.

let's say I have this project:

```
tmp
  project
    app
      stores
        a-store.js
      components
        a-component.jsx
```

the CWD is `/tmp/project` and I'm editing `app/components/a-component.jsx`. If I want to include the store, this is what happens:

![schermata 2016-10-25 alle 10 05 24](https://cloud.githubusercontent.com/assets/6401008/19677689/bdcbe4ce-9a9a-11e6-8220-343c26f3d662.png)

as you can see when adding `./` the completion start from the working directory and not the file directory.

**Comment by josefson** [comment]
As @maln0ir said, that's how vim's filename completion works.
Try loading your ```app/components/a-component.jsx``` from ```/tmp/project``` with ```vim -u NONE -N path/to/a-component.jsx```. This will open vanilla/default vim.
Now try vim default filename completion: ```./``` + <c-x><c-f> it will suggest files from CWD instead of the buffer/file directory.

**Comment by cvlmtg** [comment]
> As @maln0ir said, that's how vim's filename completion works.

sorry, I understood it as "it's already working the way you are asking". anyway, neocomplete is able to make file completion working relative to the file dir even if autochdir is not set. I've seen file completion is handled via python in completor, so I suppose it might be possibile to make it work relative to the file dir here too, but I don't know python :)

**Comment by amadeus** [comment]
I came from Neocomplete as well, and this would be super helpful to have since I often like to keep my current `pwd` at a project level, and not a file level.

**Comment by aliev** [comment]
@cvlmtg why not to use set autochdir?

**Comment by cvlmtg** [comment]
@aliev setting autochdir breaks a lot of things in my workflow. I'll try the "smart" fix even if it's annoying to see the file path in the status bar change every time I enter or leave insert mode. I still think it would be more correct fix this in completor and not in my vimrc

**Comment by SageEx** [comment]
Support for this would be really nice.

**Comment by maralla** [comment]
Now the filename completion is relative to current editing file directory. #74

**Comment by amadeus** [comment]
You are a god amongst men. Thank you!
