### ISSUE TITLE
timer_stop not working on MacVim 8.0.46 with phpcomplete

### ISSUE THREAD

**Issue by markwu** [maralla/completor.vim#35]
# Problems summary

The popup menu does not popup until I moved the mouse in GUI MacVim (mvim). But it works very well under terminal MacVim (vim)

I can't tell the problem is caused by Completor.vim, PhpComplete or MacVim it self.
## Expected

Popup menu works both GUI and Terminal MacVim
## Environment Information
- OS: OSX 10.11.6
- Vim version: 8.0.46 (MacVim)
## Provide a minimal .vimrc with less than 50 lines (Required!)

``` vim
set nocompatible
filetype off

execute 'source ~/.vim/bundle/vim-plug/plug.vim'
call plug#begin('~/.vim/bundle/')

Plug 'junegunn/vim-plug'

" Put your bundle below here
Plug 'maralla/completor.vim'
Plug 'shawncplus/phpcomplete.vim'
" Put your bundle above here

call plug#end()

syntax on
filetype plugin indent on

" Put your plugin settings below here
let g:completor_php_omni_trigger = '([$\w]+|use\s*|->[$\w]*|::[$\w]*|implements\s*|extends\s*|class\s+[$\w]+|new\s*)$'
" Put _our plugin settings above here

```
## The reproduce ways from Vim starting (Required!)
1. `:e test.php` or `set ft=php`
2. Type the following code

``` php
<?php
    $date = new DateTime();  // Popup will show here
    $date-> // Popup will not show here, until you moved the mouse corsor
```
## Screen shot (if possible)

Terminal MacVim with completor.vim & phpcomplete.vim, you can see the popup menu show up automatically.
![terminal](https://cloud.githubusercontent.com/assets/196861/19650918/8109dcd8-9a3d-11e6-8044-91e82c0dfa7d.gif)

GUI  MacVim with completor.vim & phpcomplete.vim, you can see the popup menu show up until I move the mouse cursor.
![macvim](https://cloud.githubusercontent.com/assets/196861/19650925/86d565a6-9a3d-11e6-9b80-54fc0d3d6327.gif)

**Comment by markwu** [comment]
The most weird part is this behavior only happened  in `::` and `->` .

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/issues/560

Same problem with it.

**Comment by Shougo** [comment]
MacVim timer implementation seems broken.

**Comment by markwu** [comment]
This bug is related to https://github.com/macvim-dev/macvim/issues/401

And, it already fixed by this PR https://github.com/macvim-dev/macvim/pull/417

I think this issue could be closed.
