### ISSUE TITLE
Completed words with non-latin characters are shifted to the left

### ISSUE THREAD

**Issue by maln0ir** [maralla/completor.vim#37]
Some pictures to illustrate problem. Notice places highlighted in red.
1. if there is one non-latin character in the line: 

![](https://i.imgur.com/fbtCpfa.png)
1. if there are two non-latin characters in the line:

![](https://i.imgur.com/qxEnhQm.png)

The more of such characters, the larger the shift to the left.

**Comment by maralla** [comment]
The latest commit should fix the problem. Please pull the latest commit and try it again.

**Comment by maln0ir** [comment]
Great! It works now.
