### ISSUE TITLE
Doesn't work in a buffer, which is not associated with a file?

### ISSUE THREAD

**Issue by for-coursera** [maralla/completor.vim#56]
If a buffer is not saved as a file, completor doesn't seen to work there... Is it an intended behaviour, or is there way to fix it?

**Comment by maralla** [comment]
Now it's possible to complete in an unsaved file. #75

**Comment by for-coursera** [comment]
Is it? Here's a [screencast](http://i.imgur.com/gYOe5ch.gif): 

  - at first, words are entered in an unsaved buffer, and there's no sign of the completion menu;
  - then, the file is saved, edit resumed, and the completion menu appears.

Vim 8.0.222; latest completor (updated with vim-plug just after your reply here).

**Comment by maralla** [comment]
Did you really update completor to the lastest commit?

It works pretty well in my environment: 

![com](https://cloud.githubusercontent.com/assets/2238118/22639178/a6de54b0-ec87-11e6-9d1e-33662ab95b76.gif)

**Comment by maralla** [comment]
If still not works go to the root directory of completor.vim and run:
```bash
find . -name "*.pyc" -delete
```

**Comment by for-coursera** [comment]
> Did you really update completor to the lastest commit?

I even tried to install it from the scratch to a very minimal Vim configuration. Is there any other way to ensure I'm using the latest version except using `git pull`?

  ~/.vim/tests/vim/plugged/completor.vim> git pull
   Current branch master is up to date.

(Deleting *.pyc doesn't help, too).

**Comment by maralla** [comment]
Can you run
```bash
git rev-parse HEAD
```
and check whether the output is `2c5bc721434a649c682966992cba34a4f4cd7bb1`

**Comment by for-coursera** [comment]
Sorry, I found the error, it was my vimrc after all...

Somehow it doesn't work with the [following addon](https://www.reddit.com/r/vim/comments/3dk4ng/a_little_treat_for_everyone/).

**Comment by maralla** [comment]
I pushed one more commit to enable completions for `nofile`. It should work now.

**Comment by for-coursera** [comment]
And indeed it works, thanks!
