### ISSUE TITLE
Auto install tern module use vim-plug.

### ISSUE THREAD

**Issue by laxtiz** [maralla/completor.vim#58]
i'm used gvim 8.0 on windows.
haven't gnu make. so i can't run `make js`.

I'm too lazy to manually run the command `cd path && npm install`.
but vim-plug have a post-install hook can do it.

there is a sample:
```vimL
function! TernInstall(info)
    if ( a:info.status ==# 'installed' || a:info.force ) && executable('npm')
        call system('cd ./pythonx/completers/javascript && npm install')
    endif
endfunction

Plug 'maralla/completor.vim', {
            \ 'do': function('TernInstall')
            \ }
```

then run `PlugUpdate! completor.vim`

for who need.

**Comment by aliev** [comment]
@laxtiz try

``
Plug 'maralla/completor.vim', {'do': 'make js'}
``

**Comment by aliev** [comment]
@laxtiz try this one
Plug 'maralla/completor.vim', {'do': 'cd pythonx/completers/javascript && npm install'}
