### ISSUE TITLE
Can't  re-enable a default blacklisted filetype

### ISSUE THREAD

**Issue by edwlarkey** [maralla/completor.vim#62]
I have tried `let g:completor_blacklist = ['tagbar', 'qf', 'netrw', 'unite']` and `let g:completor_whitelist = ['vimwiki']`, but those doesn't enable completion of `vimwiki`.

I tried those options individually and together.

**Comment by maralla** [comment]
The pr #68 make it possible to overwrite default blacklist. Now the completion of `vimwiki` can be enabled using:
```vim
let g:completor_blacklist = ['tagbar', 'qf', 'netrw', 'unite']
```

**Comment by edwlarkey** [comment]
Verified that it works. Thanks a lot! Closing.
