### ISSUE TITLE
Error detected while processing completor/utils.vim

### ISSUE THREAD

**Issue by predmijat** [maralla/completor.vim#66]
Hi,

I've started getting this error today, not sure what caused it. I didn't update plugins for a while (using vim-plug). I did update brew packages, not sure if vim was on the list. Anyway, here's the error:

```
Error detected while processing /Users/predmijat/dotfiles/.vim/plugins/completor.vim/autoload/completor/utils.vim:
line   65:
E126: Missing :endfunction
Error detected while processing function <lambda>2[1]..<SNR>94_complete:
line    4:
E117: Unknown function: completor#utils#get_completer
E15: Invalid expression: completor#utils#get_completer(s:status.ft, s:status.input)
line    5:
E121: Undefined variable: info
E116: Invalid arguments for function empty(info) | return | endif
E15: Invalid expression: empty(info) | return | endif
line    6:
E121: Undefined variable: info
E15: Invalid expression: info
line    8:
E121: Undefined variable: is_sync
```

As far as I can tell, there's no endfuction missing, variable info is defined...

vim is installed via brew - `brew install vim --with-luajit`, I've tried to remove it with `brew uninstall --force vim` and reinstall it, error persists.

Thanks!

**Comment by cwonrails** [comment]
I just ran into this as well while trying to edit a go file.

**Comment by predmijat** [comment]
I have go related plugins, but this occurs with any extension.

**Comment by cwonrails** [comment]
Can confirm - just tried to edit a python file, same results.

**Comment by cvlmtg** [comment]
same error here

**Comment by toejough** [comment]
this happens after every character press for me, which makes vim nearly unusable.  Uninstalling the plugin & going without completion till this is fixed, or till there's a workaround discovered.

**Comment by amadeus** [comment]
I am pretty sure this is an issue related to a recent vim update, since Completor has not updated in a while.

**Comment by rgerardi** [comment]
I agree with @amadeus it is related to a vim update.
I executed some tests and here are the results:
Issue occurs with versions: 8.0.0187 and 8.0.0197
No issues with version 8.0.0172 and below.

**Comment by maralla** [comment]
@predmijat The pr #67 fixed this problem.

**Comment by amadeus** [comment]
Awesome, seems to work great! Thanks!
