### ISSUE TITLE
What about java?

### ISSUE THREAD

**Issue by ehzawad** [maralla/completor.vim#7]
Can I make it usable for java?

**Comment by deathbeam** [comment]
I think it is doable, just use for example eclim and set it to use autocomplete, and then just use exactly same trigger regex as JavaScript uses:

```viml
let g:completor_java_omni_trigger = '\w+$|[\w\)\]\}\'\"]+\.\w*$'
```

Do not have time to test it, but it should work.

**Comment by ehzawad** [comment]
E15: Invalid expression: '\w+$|[\w\)\]\}\\\'\"]+\.\w*$' @deathbeam not working rather throwing an error
