### ISSUE TITLE
completor.vim freeze when complete c code

### ISSUE THREAD

**Issue by jsfaint** [maralla/completor.vim#70]
Rencently I start migrating some old plugin with the modern replacement.
Then I found completor.vim, it's very impressive.

But I meet an issue that c completion freeze on windows.

My environment is windows 10 + vim8 + python3.5

When I input some characters and the clang completion was triggered(no competion window showed up), vim will freeze until I press ctrl-c

I tried python completion it works fine.
And I can't reproduce this issue on linux and macos

Did anyone meet the same issue with me?
Thanks

**Comment by mkarpoff** [comment]
I have the same problem with the same environment.

**Comment by tomleb** [comment]
I have the same problem on Linux. Only experienced it with C code.

**Comment by mkarpoff** [comment]
I also does it in C++ in my case

**Comment by jsfaint** [comment]
@tomleb I can reproduce this issue on archlinux with C code too. 😢

**Comment by ruslashev** [comment]
I have same issue, with addition(?) of memory being allocated non-stop

**Comment by terminull** [comment]
Bumping, can confirm on vim8. Removing completor.vim from my vimrc and the no more freezes.

**Comment by Glamhoth** [comment]
Confirming, gVim 8 on Windows 8.1 x64. Please, do something with it.

**Comment by junhyeokahn** [comment]
same on me. hope it is fixed soon

**Comment by dutchgecko** [comment]
If I'm not mistaken this issue has been fixed by https://github.com/maralla/completor.vim/pull/121

**Comment by jsfaint** [comment]
Confirmed on windows, this issue was resolved.
