### ISSUE TITLE
Support NeoSnippet

### ISSUE THREAD

**Issue by SageEx** [maralla/completor.vim#72]
Hi, thanks for this plugin.

Could you also support a Neosnippet source ?

**Comment by maralla** [comment]
This repo [completor-neosnippet](https://github.com/maralla/completor-neosnippet) implemented neosnippet completion. Upgrade completor.vim to the latest commit then install completor-neosnippet.

**Comment by SageEx** [comment]
Thanks a lot for the fast reply 👍 .
