### ISSUE TITLE
Is it possible to force a fallback completer?

### ISSUE THREAD

**Issue by for-coursera** [maralla/completor.vim#79]
Is it possible to disable a semantic completer for a buffer / file mask / file type, and switch to a fallback one (i.e., to a buffer completer)?

**Comment by maralla** [comment]
You can disable a file type using `let g:completor_disable_{filetype} = 1`.

For example to disable semantic completion for `python`:
```vim
let g:completor_disable_python = 1
```

**Comment by for-coursera** [comment]
But it doesn't fallback to the buffer completer after that, am I right? It seems like it just disables completor entirely for that filetype?

**Comment by maralla** [comment]
I just pushed a commit. Now it will fallback to buffer completion.

**Comment by for-coursera** [comment]
Super, thanks!
