### ISSUE TITLE
Custom triggers?

### ISSUE THREAD

**Issue by dbmrq** [maralla/completor.vim#8]
Good job here. :)

I'm not sure how this works behind the scenes, but [vimtex](https://github.com/lervag/vimtex/) has its own omni completion function (it completes bibliography entry names, source files to include and so on) and when using NeoComplete or YouCompleteMe you can set up custom triggers to call it, like this:

```vim
  let g:neocomplete#sources#omni#input_patterns.tex =
        \ '\v\\%('
        \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
        \ . '|hyperref\s*\[[^]]*'
        \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|%(include%(only)?|input)\s*\{[^}]*'
        \ . '|\a*(gls|Gls|GLS)(pl)?\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . ')'
```

([The full documentation is here.](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L1537))

Is there a way to do something like that here?

Also those other plugins work with UltiSnips too, completing the snippet triggers. That would be great!

**Comment by maralla** [comment]
Now you can config tex completion like this:
```vim
let g:completor_tex_omni_trigger = '\\\\(:?'
        \ .  '\w*cite\w*(?:\s*\[[^]]*\]){0,2}\s*{[^}]*'
        \ . '|\w*ref(?:\s*\{[^}]*|range\s*\{[^,}]*(?:}{)?)'
        \ . '|hyperref\s*\[[^]]*'
        \ . '|includegraphics\*?(?:\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|(?:include(?:only)?|input)\s*\{[^}]*'
        \ . '|\w*(gls|Gls|GLS)(pl)?\w*(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|includepdf(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|includestandalone(\s*\[[^]]*\])?\s*\{[^}]*'
        \ .')$'
```

**Comment by dbmrq** [comment]
Uhm, now I'm getting this:

```
Error detected while processing function <lambda>5[1]..<SNR>135_complete[13]..<SNR>135_trigger[4]..completor#utils#get_completions:
line    7:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/daniel/.vim/bundle/completor.vim/pythonx/completers/_omni.py", line 41, in parse
    if start < 0:
TypeError: unorderable types: str() < int()
```

**Comment by maralla** [comment]
The pr #15 fixed the problem. You can try it again.

**Comment by dbmrq** [comment]
Awesome, it's looking great! 🎉 
Now I just miss the UltiSnips integration, but I can live without it for now.
Thank you!

**Comment by maralla** [comment]
Now it has UltiSnips integration.

**Comment by dbmrq** [comment]
Awesome, thank you! ❤️
I'm on a trip right now, so I won't be be to test it for a few days, but I'll close this issue then, and I'll reopen id there are any problems.
Thabks again for your amazing work on this.
