### ISSUE TITLE
Performance issues??

### ISSUE THREAD

**Issue by Junnplus** [maralla/completor.vim#86]
<img width="806" alt="qq20170318-175749 2x" src="https://cloud.githubusercontent.com/assets/8097526/24071046/9a42b128-0c04-11e7-91b5-e51ee6b9a75d.png">
<img width="1272" alt="qq20170318-175728 2x" src="https://cloud.githubusercontent.com/assets/8097526/24071047/9b87fa16-0c04-11e7-9759-bb7e549e9151.png">

**Comment by maralla** [comment]
The problem should be fixed. Please update.
