### ISSUE TITLE
Toggling completor On/Off

### ISSUE THREAD

**Issue by chew-z** [maralla/completor.vim#88]
What is the proper way to toggle this plugin On/Off completely? I have been trying to get through your code but couldn't grasp it.

My use case is that I find autocompletion distracting 90% of the time and super useful 10% of the time. I am using completor only for Python with Jedi and don't need file or buffer completion.

Now for some reason completor  doesn't seem to work when I set autocomplete on Tab as per README - which would be a solution. It works on Tab with buffers but with Jedi only when I have auto trigger set to 1.

`let g:completor_auto_trigger = 1`

Constant autocompletion is an overkill for me. I have been trying to move this option to ftplugin/python.vim but that has obvious side-effects of re-enabling completor in other buffers as well.

So I have created small function using completor#disable() and completor#enable()

```
let g:completor_toggle = 1
function! ToggleAutocomplete()
    if g:completor_toggle == 1
        let g:completor_toggle = 0
        call completor#disable()
    else
        let g:completor_auto_toggle = 1
        call completor#enable()
    endif
endfunction
```

it seems to work but completor automagically re-enables itself after few keystrokes. I do not understand why and how.

**Comment by chew-z** [comment]
I have made it work as I like it with SuperTab without even remapping <Tab> . It took me some time reading through small print in SuperTab docs. 

The trick is in setting buffer option in ftplugin/python.vim

`let b:SuperTabContextDefaultCompletionType = '<C-x><C-u>'`

which makes SuperTab trying to call completition with Completor in Python.

For the posterity my .vimrc [all SuperTab options are default.]

```
let g:completor_auto_trigger = 0
" Supertab
let g:SuperTabDefaultCompletionType = "<C-p>"
let g:SuperTabDefaultCompletionType = 'context'
let g:SuperTabContextTextOmniPrecedence = ['&completefunc', '&omnifunc']
let g:SuperTabMappingForward = "<Tab>"
let g:SuperTabCrMapping = 1
```

My question - how to toggle Completor On/Off still remains relevant I think but less urgent.

**Comment by maralla** [comment]
You can use [this option](https://github.com/maralla/completor.vim/blob/master/doc/completor.txt#L130) to allow completion only for specified file types.

To totally disable completion you can use command `CompletorDisable`, To reenable use `CompletorEnable`.

**Comment by chew-z** [comment]
Thank you. I have figured that out going through code. I use `call completor#enable()`

Finally I have removed SuperTab at least for now - too much spaghetti thrown at the wall. 

I am really, really enjoying using Completor. Works really nice. 

However I am not entirely understanding how it works. 

1) Why completefunc turns out empty so often? Isn't it populated too late?

2) How do you insert snippets from Ultisnips? I see them on the list but using <Tab> or <Ctrl-Y> or <CR> doesn't do anything. So I use Ultisnips shortcut instead but is it the right way to go?

**Comment by chew-z** [comment]
After some time I like your plugin more and more.

If I may suggest however there could be a buffer version of `completor_auto_trigger `. That way one could enable automatic completion for certain file types with `let b:completor_auto_trigger = 1`.
This is different then whitelisting some filetypes.

I also find the logic of completor (with auto_trigger off) a little frustrating. If I got it right from reading code CompletorEnable really comes to calling s:set_events() function which is calling s:on_text_change() and s:on_insert_char_pre().

The completion works only after typing some word (for example `let`) but if you move cursor to another line and put it on exact same `let` no completion happens. This is counterintuitive and frustrating. If completor is enabled it should trigger always and have the same efffect on identical words.

And now embarrasing question. What would g:completor_text_omni_trigger regex look like? I couldn't figure that out for thesaurus completion in plain text or markdown.

**Comment by maralla** [comment]
> Why completefunc turns out empty so often? Isn't it populated too late?

Currently the completion status is tracked from the last completion triggered by inputting some chars. If the cursor moved to a different location with the same completion prefix the status will not change if no char inputted so completion menu may not popup at the right place. So the completion result is cleared after every completion.

> How do you insert snippets from Ultisnips? I see them on the list but using `<Tab>` or `<Ctrl-Y>` or `<CR>` doesn't do anything. So I use Ultisnips shortcut instead but is it the right way to go?

The snippets on the completion list are only a reminder to show that there are some utilsnips here. It should be triggered using Ultisnips shortcut.

> And now embarrasing question. What would g:completor_text_omni_trigger regex look like? I couldn't figure that out for thesaurus completion in plain text or markdown.

`dictionary` and `thesaurus` completions are not supported by completor currently. But you can use [vim builtin completions](http://vim.wikia.com/wiki/Dictionary_completions).
