### ISSUE TITLE
Add support for other JavaScript filetypes like javascript.jsx

### ISSUE THREAD

**Issue by ahmedelgabri** [maralla/completor.vim#91]
It took me nearly 20mins to figure out why the JavaScript completion was not working at all when I realized that I set my JavaScript `ft=javascript.jsx` & it seems that in order for it to work it `ft` must be [`javascript` only](https://github.com/maralla/completor.vim/blob/master/pythonx/completers/javascript/__init__.py#L13). It will be nice to support other filetypes too.

**Comment by maralla** [comment]
You can use the option `g:completor_filetype_map` to add support for `javascript.jsx`:
```vim
" In vimrc
let g:completor_filetype_map = {'javascript.jsx': 'javascript'}
```

**Comment by ahmedelgabri** [comment]
Thanks, I guess you need to add that to `:h` :)

**Comment by ahmedelgabri** [comment]
It still doesn't work though, only when I change `ft` to `javascript`

**Comment by maralla** [comment]
Well it works pretty good in my environment:

![com](https://cloud.githubusercontent.com/assets/2238118/24743728/e2d66114-1ae1-11e7-9382-3d62fe2a31c8.gif)

**Comment by ahmedelgabri** [comment]
Here is gif on my env

![completor](https://cloud.githubusercontent.com/assets/63876/24744341/062b1824-1ab2-11e7-93d3-9393bd71b7a8.gif)

Here is what I added to my [`init.vim`](https://github.com/ahmedelgabri/dotfiles/blob/HEAD/neovim/.config/nvim/init.vim)

```vim
Plug 'maralla/completor.vim', { 'do': 'make js' }
let g:completor_filetype_map = {'javascript.jsx': 'javascript'}
let g:completor_completion_delay = 10
```

**Comment by maralla** [comment]
This commit #94 should fix the problem. Please update and try it again.

**Comment by ahmedelgabri** [comment]
It works now, thank @maralla 👍
